### ISSUE TITLE
Mejorar diseño de formulario de contacto

### ISSUE THREAD

**Issue by mentorrolling** [mentorrolling/proyecto-curso-git#6]
El formulario debe estar centrado y tener más espacio entre sus elementos, en especial el botón

![image](https://github.com/mentorrolling/proyecto-curso-git/assets/68254100/9bbacd9e-0699-41ca-aba3-526c5992d8a7)

**Comment by pmarino2013** [comment]
Resuelto el issue con el nuevo diseño, se crea pull request con rama contacto.
![image](https://github.com/mentorrolling/proyecto-curso-git/assets/35234004/5f39e4dc-7d16-4384-aabb-2f8b2bfe1509)
